/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/site'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminProcurementRouteImport } from './routes/admin.procurement'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminWorkforceRouteImport } from './routes/admin.workforce'
import { Route as SiteIndexRouteImport } from './routes/site.index'
import { Route as SiteDashboardRouteImport } from './routes/site.dashboard'
import { Route as SiteDocumentsRouteImport } from './routes/site.documents'
import { Route as SiteDprRouteImport } from './routes/site.dpr'
import { Route as SiteEquipmentRouteImport } from './routes/site.equipment'
import { Route as SiteInventoryRouteImport } from './routes/site.inventory'
import { Route as SiteIssuesRouteImport } from './routes/site.issues'
import { Route as SiteMaterialsRouteImport } from './routes/site.materials'
import { Route as SiteProjectsRouteImport } from './routes/site.projects'
import { Route as SiteWorkforceRouteImport } from './routes/site.workforce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcurementRoute = AdminProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkforceRoute = AdminWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDashboardRoute = SiteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocumentsRoute = SiteDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDprRoute = SiteDprRouteImport.update({
  id: '/dpr',
  path: '/dpr',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEquipmentRoute = SiteEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInventoryRoute = SiteInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIssuesRoute = SiteIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMaterialsRoute = SiteMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsRoute = SiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWorkforceRoute = SiteWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/site': typeof SiteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/site/dashboard': typeof SiteDashboardRoute
  '/site/documents': typeof SiteDocumentsRoute
  '/site/dpr': typeof SiteDprRoute
  '/site/equipment': typeof SiteEquipmentRoute
  '/site/inventory': typeof SiteInventoryRoute
  '/site/issues': typeof SiteIssuesRoute
  '/site/materials': typeof SiteMaterialsRoute
  '/site/projects': typeof SiteProjectsRoute
  '/site/workforce': typeof SiteWorkforceRoute
  '/admin/': typeof AdminIndexRoute
  '/site/': typeof SiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/site/dashboard': typeof SiteDashboardRoute
  '/site/documents': typeof SiteDocumentsRoute
  '/site/dpr': typeof SiteDprRoute
  '/site/equipment': typeof SiteEquipmentRoute
  '/site/inventory': typeof SiteInventoryRoute
  '/site/issues': typeof SiteIssuesRoute
  '/site/materials': typeof SiteMaterialsRoute
  '/site/projects': typeof SiteProjectsRoute
  '/site/workforce': typeof SiteWorkforceRoute
  '/admin': typeof AdminIndexRoute
  '/site': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/site': typeof SiteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/site/dashboard': typeof SiteDashboardRoute
  '/site/documents': typeof SiteDocumentsRoute
  '/site/dpr': typeof SiteDprRoute
  '/site/equipment': typeof SiteEquipmentRoute
  '/site/inventory': typeof SiteInventoryRoute
  '/site/issues': typeof SiteIssuesRoute
  '/site/materials': typeof SiteMaterialsRoute
  '/site/projects': typeof SiteProjectsRoute
  '/site/workforce': typeof SiteWorkforceRoute
  '/admin/': typeof AdminIndexRoute
  '/site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/site'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/procurement'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/workforce'
    | '/site/dashboard'
    | '/site/documents'
    | '/site/dpr'
    | '/site/equipment'
    | '/site/inventory'
    | '/site/issues'
    | '/site/materials'
    | '/site/projects'
    | '/site/workforce'
    | '/admin/'
    | '/site/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/procurement'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/workforce'
    | '/site/dashboard'
    | '/site/documents'
    | '/site/dpr'
    | '/site/equipment'
    | '/site/inventory'
    | '/site/issues'
    | '/site/materials'
    | '/site/projects'
    | '/site/workforce'
    | '/admin'
    | '/site'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/site'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/procurement'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/workforce'
    | '/site/dashboard'
    | '/site/documents'
    | '/site/dpr'
    | '/site/equipment'
    | '/site/inventory'
    | '/site/issues'
    | '/site/materials'
    | '/site/projects'
    | '/site/workforce'
    | '/admin/'
    | '/site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/procurement': {
      id: '/admin/procurement'
      path: '/procurement'
      fullPath: '/admin/procurement'
      preLoaderRoute: typeof AdminProcurementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workforce': {
      id: '/admin/workforce'
      path: '/workforce'
      fullPath: '/admin/workforce'
      preLoaderRoute: typeof AdminWorkforceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/site/': {
      id: '/site/'
      path: '/'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/dashboard': {
      id: '/site/dashboard'
      path: '/dashboard'
      fullPath: '/site/dashboard'
      preLoaderRoute: typeof SiteDashboardRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/documents': {
      id: '/site/documents'
      path: '/documents'
      fullPath: '/site/documents'
      preLoaderRoute: typeof SiteDocumentsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/dpr': {
      id: '/site/dpr'
      path: '/dpr'
      fullPath: '/site/dpr'
      preLoaderRoute: typeof SiteDprRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/equipment': {
      id: '/site/equipment'
      path: '/equipment'
      fullPath: '/site/equipment'
      preLoaderRoute: typeof SiteEquipmentRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/inventory': {
      id: '/site/inventory'
      path: '/inventory'
      fullPath: '/site/inventory'
      preLoaderRoute: typeof SiteInventoryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/issues': {
      id: '/site/issues'
      path: '/issues'
      fullPath: '/site/issues'
      preLoaderRoute: typeof SiteIssuesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/materials': {
      id: '/site/materials'
      path: '/materials'
      fullPath: '/site/materials'
      preLoaderRoute: typeof SiteMaterialsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/projects': {
      id: '/site/projects'
      path: '/projects'
      fullPath: '/site/projects'
      preLoaderRoute: typeof SiteProjectsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/workforce': {
      id: '/site/workforce'
      path: '/workforce'
      fullPath: '/site/workforce'
      preLoaderRoute: typeof SiteWorkforceRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminProcurementRoute: typeof AdminProcurementRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminWorkforceRoute: typeof AdminWorkforceRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminProcurementRoute: AdminProcurementRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminWorkforceRoute: AdminWorkforceRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SiteRouteChildren {
  SiteDashboardRoute: typeof SiteDashboardRoute
  SiteDocumentsRoute: typeof SiteDocumentsRoute
  SiteDprRoute: typeof SiteDprRoute
  SiteEquipmentRoute: typeof SiteEquipmentRoute
  SiteInventoryRoute: typeof SiteInventoryRoute
  SiteIssuesRoute: typeof SiteIssuesRoute
  SiteMaterialsRoute: typeof SiteMaterialsRoute
  SiteProjectsRoute: typeof SiteProjectsRoute
  SiteWorkforceRoute: typeof SiteWorkforceRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteDashboardRoute: SiteDashboardRoute,
  SiteDocumentsRoute: SiteDocumentsRoute,
  SiteDprRoute: SiteDprRoute,
  SiteEquipmentRoute: SiteEquipmentRoute,
  SiteInventoryRoute: SiteInventoryRoute,
  SiteIssuesRoute: SiteIssuesRoute,
  SiteMaterialsRoute: SiteMaterialsRoute,
  SiteProjectsRoute: SiteProjectsRoute,
  SiteWorkforceRoute: SiteWorkforceRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
